# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).


[package]
name = "icu_datetime_bag_v2"
description = "New components bag API for DateTimeFormatter"
version = "0.1.0"
authors = ["The ICU4X Project Developers"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/unicode-org/icu4x"
license = "Unicode-DFS-2016"
# Keep this in sync with other crates unless there are exceptions
include = [
    "src/**/*",
    "examples/**/*",
    "benches/**/*",
    "tests/**/*",
    "Cargo.toml",
    "LICENSE",
    "README.md",
]

[lib]
bench = false       # This option is required for Benchmark CI
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icu_provider = { version = "1.0.0-beta1", path = "../../provider/core", features = ["macros"] }
icu_datetime = { version = "1.0.0-beta1", path = "../../components/datetime", features = ["datagen", "experimental"] }
bitflags = "1.3"
displaydoc = { version = "0.2.3", default-features = false }
yoke = { version = "0.6.0", path = "../../utils/yoke", features = ["derive"] }
zerovec = { version = "0.8", path = "../../utils/zerovec", features = ["yoke"] }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"], optional = true }
databake = { version = "0.1.0", path = "../../utils/databake", optional = true, features = ["derive"] }

[features]
std = ["icu_provider/std"]
default = []
serde = ["dep:serde", "icu_provider/serde"]
datagen = ["serde", "databake"]
